manifest.chrome.json, manifest.firefox.json, manifest.json, src/index.js, src/options.html, src/options.min.js
=> Added the function of translating song lyrics

src/index.js
forgot to return when testing, my bad
=> Translation error in a new line

README.md, manifest.chrome.json, manifest.firefox.json, manifest.json, src/index.css, src/index.js, www/pages/index.tsx
=> Wrapper rewrite & Loading states

.gitmodules
=> feat: added submodule to api

README.md, manifest.json, scripts/bump-ver.sh, src/index.js, src/options.html, templates/manifest.chrome.json, templates/manifest.firefox.json
=> fix: fallback lyrics not showing up sometimes

.github/ISSUE_TEMPLATE/BUG_REPORT.yml, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
Modified format - Github templates
=> chore: modified format

README.md, manifest.json, src/index.css, src/options.html, templates/manifest.chrome.json, templates/manifest.firefox.json
Fixed miniplayer getting translated horizontally due to stylesheet. 
Fixes #31
=> fix: miniplayer

README.md, manifest.json, src/index.css, src/options.html, templates/manifest.chrome.json, templates/manifest.firefox.json
Profile dropdown dots due to invalid css
Fixes #33 
| <img width="285" alt="image" src="https://github.com/boidushya/better-lyrics/assets/26746725/296eb886-8883-4baf-b7c5-a06ea5a130e2"> | <img width="292" alt="image" src="https://github.com/boidushya/better-lyrics/assets/26746725/0fa43cbd-d7b1-45c8-b02d-8a4d1a994ace"> |
=> fix: profile dropdown dots due to invalid css

src/index.css
Reduced the distance between the original song line and translation.
Fixes # (issue)
| ![Screenshot 2024-08-02 195747](https://github.com/user-attachments/assets/54eb896b-699f-42c4-8c8f-7ed289c82a84) | ![Screenshot 2024-08-02 195721](https://github.com/user-attachments/assets/dd3aaefd-7210-4070-8433-5498e0f39af4) |
=> reduced the distance between the original song line and translation

src/index.css
Fixed overlapping translation lines
Fixes # (issue)
| ![before](https://github.com/user-attachments/assets/03b3942a-f739-4c83-bd19-2c65b9764921) | ![after](https://github.com/user-attachments/assets/054f930f-832c-4ae0-8049-9a45340b5691) |
=> fixed overlapping translation lines

README.md, manifest.json, scripts/bump-ver.sh, src/index.js, src/options.html, templates/manifest.chrome.json, templates/manifest.firefox.json
Disabled auto scroll if end of song is reached
=> fix: disabled auto scroll if end of song is reached

.github/ISSUE_TEMPLATE/BUG_REPORT.yml, README.md
Readme and github issue template changes.
=> chore: added FAQ to readme

README.md
Section about permissions and explanation for the same
Fixes #55
=> chore(README): Section about permissions

README.md, manifest.json, src/index.css, src/options/editor.js, src/options/options.css, src/options/options.html, src/options/options.js, templates/manifest.chrome.json, templates/manifest.firefox.json, www/styles/globals.css
I changed the CSS, such that the theme song should support with better lyrics.
Please include a summary of the changes and the related issues. Please also include relevant motivation and context. List any dependencies that are required for this change.
| ![image](https://github.com/user-attachments/assets/cc5faefb-6aeb-4208-8347-3678d8dfba7d) | ![image](https://github.com/user-attachments/assets/21e1b5a8-f25d-4a13-938e-e74ca752b74f)|
=> ThemeSong compat, Auto Save, Themes

README.md, manifest.json, src/options/options.html, templates/manifest.chrome.json, templates/manifest.firefox.json
=> chore: bumped version

README.md, manifest.json, src/options/editor.js, src/options/options.css, src/options/options.html, templates/manifest.chrome.json, templates/manifest.firefox.json
- Moved theme selector to homepage
=> fix: theme selector position

src/background.js, src/core/constants.js, src/modules/settings/settings.js, src/modules/ui/dom.js, src/modules/ui/observer.js, src/options/options.js
=> Myse1f change setting without refresh

README.md, STYLING.md, manifest.json, src/core/constants.js, src/index.css, src/modules/lyrics/lyrics.js, src/modules/lyrics/translation.js, src/options/options.html, src/options/options.js, templates/manifest.chrome.json, templates/manifest.firefox.json
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
| [Paste Image Here] | [Paste Image Here] |
=> romanization

README.md, manifest.json, src/index.css, src/options/options.html, templates/manifest.chrome.json, templates/manifest.firefox.json
Hotfix for stylized animations not working
=> fix: stylized animations not working

src/core/constants.js, src/core/storage.js, src/index.js, src/modules/lyrics/lyrics.js, src/options/options.css, src/options/options.html, src/options/options.js
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
|NA  | <img width="1094" alt="Screenshot 2024-10-11 at 5 41 11 PM" src="https://github.com/user-attachments/assets/e190c212-c505-452c-9362-eb6e6b469b1f"> |
=>  lyrics caching in localstorage for quick retrieval

src/core/storage.js, src/index.js, src/modules/lyrics/lyrics.js, src/modules/settings/settings.js, src/options/options.js
Migrated from storage.sync to localStorage due to size limitations
=> fix: moved cache from sync to localStorage

src/script.js
The fix is in: 175d131b13e2a0420ef8656c53b7a7980e938d8f
Also renamed some of the variables & methods to more clearly represent their purpose.
=> Fix the tickLyricsInterval from being stopped while the page loads

src/index.js, src/modules/ui/dom.js
Scroll top issue on window change
=> fix(DOM): scroll to top on window change

src/index.js, src/modules/ui/observer.js
Use an alternative way to fix the auto lyric tab switching not working
=> Fix auto switch

src/index.css, src/index.js, src/modules/lyrics/lyrics.js, src/modules/ui/dom.js
We still have issues regarding the animation from the loader which aren't yet resolved by this.
=> Fix scrolling to top when they're isn't a lyric at 0s

scripts/build-chrome.sh, scripts/build-edge.sh, scripts/build-firefox.sh, src/modules/ui/dom.js, templates/manifest.chrome.json, templates/manifest.firefox.json
Didn't realize that the builds scripts use different manifest files, so I've updated those too here.
I'd double check that the built versions work (I couldn't get the build scripts to work on my machine), but I believe it should be fine now.
=> update manifest and build files

src/modules/lyrics/lyrics.js, src/modules/ui/observer.js
Fix issues with the lyrics tab being disabled on initial load.g
Make sure the lyrics we fetch match the YT ones before displaying them.
Add version data to lyrics, so that we can easily invalidate old caches when we update the extension
=> Refactor lyric fetching bug fix + filter out incorrect lyrics

scripts/lint.sh, src/index.css, src/modules/ui/dom.js, src/options/editor.js
- firefox saving
- autoscroll top offset multiplier (will be added to GUI later)
- added `./scripts/lint.sh` for easier linting and formatting
=> fix: fixed saving for firefox and minor styling and functionality changes for autosaving

.vscode/settings.json, src/core/constants.js, src/modules/lyrics/lyrics.js, src/modules/lyrics/providers.js, src/modules/ui/dom.js, src/modules/ui/observer.js, src/options/options.html, src/options/options.js
Added an option for users to select default provider (BetterLyrics / LRCLib)
=> feat: added choice for users to select default provider

src/index.css, src/modules/ui/dom.js
- Slightly changes the wobble animation to help it feel more in sync with the highlighting of the text.  
- Separates highlighting and scrolling of lyrics to allow scrolling to happen slightly before text highlighting 
TODO: make the values configurable?
=> improve scroll animation timings

src/index.css
=> fix bug #113

src/index.css, src/index.js, src/modules/ui/dom.js, src/modules/ui/observer.js, src/options/options.js, templates/manifest.firefox.json
* Updated `templates/manifest.firefox.json` to use Manifest V3, to align with the manifest for chrome
* Modified `src/index.css` to use `alpha` mask mode and updated gradient colors to improve performance slightly.
* Fix lyrics not ticking in the mobile ui style.
* Added `disableInertWhenFullscreen` in `src/modules/ui/observer.js` to prevent the `inert` attribute from blocking interactions with side-panel elements in fullscreen mode.
* Implemented tab scroll state persistence in `src/modules/ui/observer.js`, allowing users to return to their previous scroll position when switching tabs.
* Fix cache being cleared with unrelated settings changes
=> Misc Bug Fixes

src/earlyInject.js, src/modules/ui/observer.js
- Remove a few `console.log` accidentally left in.
- Fix issues when also using uBlock Origin by making the lyrics sniffing more robust.
- Ensure lyrics tab is always selected in full screen.
=> Fix "No Internet Connection" with uBlock Origin + a few misc fixes

src/options/themes.js
- Added 2 new themes
- Minimal
- Luxury Glass
=> feat: new themes (Minimal & Luxury Glass)

src/options/themes.js
- Updated minimal theme v1.3.0
=> chore(theme): updated minimal
